version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customers
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"