version: '3.5'
services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customers
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  app:
    image: "demo-spring-boot:0.0.1-SNAPSHOT"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_demo:5432/customers
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATA_REDIS_HOST=redis
      - MANAGEMENT_ENDPOINT_ENV_SHOW_VALUES=ALWAYS
    depends_on:
      - redis
      - postgres
    profiles:
      - app
    ports:
      - "8080:8080"