GET http://localhost:8080/actuator/health
Accept: application/json

###
POST http://localhost:8080/customer
Content-Type: application/json

{"firstName":  "John", "lastName": "Smith4"}

###
GET http://localhost:8080/customer/80a5ef99-d9f6-46c1-94bf-34bfcae2abf3
Accept: application/json

###
GET http://localhost:8080/actuator/info
Accept: application/json
###

GET http://localhost:8080/actuator/env
Accept: application/json
###