POST http://localhost:8080/customer
Content-Type: application/json

{"firstName":  "John", "lastName": "Smith"}

###
GET http://localhost:8080/customer/a8f4086e-2278-480d-b740-3e064c24ef98
Accept: application/json
###
GET http://localhost:8080/actuator/info
Accept: application/json
###

