POST http://localhost:8080/customer
Content-Type: application/json

{"firstName":  "John", "lastName": "Smith"}

###
GET http://localhost:8080/customer/3f47a080-c345-4544-a35f-629fb5a2f5d2
Accept: application/json
###
GET http://localhost:8080/actuator/info
Accept: application/json
###

