#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: git-github-ssh
  namespace: developer-ns
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: #@ data.values.sshprivatekey
  identity: #@ data.values.identity
  identity.pub: #@ data.values.identitypub
  known_hosts: #@ data.values.knownhosts