spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: admin
    password: admin
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "health", "info" ]
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
## Configuring info endpoint
info:
  app:
    name: Spring Boot Application Demo
