spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: admin
    password: admin
  data:
    redis:
      host: ${spring.redis.host:localhost}
      password: ${spring.redis.password:admin}
  application:
    name: demo-spring-boot
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "env", "prometheus" ]
  endpoint:
    env:
      enabled: true
#      show-values: always
    health:
      probes:
        enabled: true
    info:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  health:
    redis:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
## Configuring info endpoint
info:
  app:
    name: Spring Boot Application Demo

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"