version: '3.8'

services:
  app:
    container_name: app_demo
    image: "demo-spring-boot:0.0.1-SNAPSHOT"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customers
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customers
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"