---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    apps.tanzu.vmware.com/language: java
    app.kubernetes.io/part-of: demo-spring-boot
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: demo-spring-boot
    tanzu.app.live.view.application.flavours: spring-boot
    tanzu.app.live.view.application.actuator.port: "8081"

  name: demo-spring-boot
  namespace: developer-ns
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/min-scale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/language: java
    - name: gitops_ssh_secret
      value:
        git-github-ssh
  serviceClaims:
  - name: db1
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: postgres-1
  - name: red1
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: redis-1
  source:
    git:
      ref:
        branch: master
      url: ssh://git@github.com/omocquais-p/demo-spring-boot.git
