---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"  # docs glitch: they show the value without quotes
    apps.tanzu.vmware.com/language: java
    app.kubernetes.io/part-of: demo-spring-boot
    apps.tanzu.vmware.com/auto-configure-actuators: "false"
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: demo-spring-boot
    tanzu.app.live.view.application.flavours: spring-boot
#    tanzu.app.live.view.application.actuator.port: "8081"
  name: demo-spring-boot
  namespace: apps
spec:
  # Resource constraints for the application. See
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  # +optional
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      memory: 256Mi
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
    - name: BP_NATIVE_IMAGE
      value: "false"
    - name: BP_MAVEN_BUILD_ARGUMENTS
      value: "-Dmaven.test.skip=true --no-transfer-progress package"
  env:
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: health,info,prometheus
    - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
      value: http://tempo:9411/api/v2/spans
    - name: ENABLE_LOKI
      value: true
    - name: MANAGEMENT_TRACING_ENABLED
      value: true
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/min-scale: "1"
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/language: java
    - name: gitops_server_address
      value: ssh://git@github.com  # important to have the protocol ssh://
    - name: gitops_repository_owner
      value: omocquais-p
    - name: gitops_repository_name
      value: demo-spring-boot-gitops
    - name: gitops_branch
      value: dev
    - name: gitops_commit_message
      value: "Update demo-spring-boot config"
    - name: gitops_ssh_secret
      value: git-github-ssh
  serviceClaims:
  - name: db1
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: postgres-1
  - name: red1
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: redis-1
  source:
    git:
      ref:
        branch: master
      url: ssh://git@github.com/omocquais-p/demo-spring-boot.git
