package com.example.demospringboot.service;

import com.example.demospringboot.dto.CustomerDTO;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.springframework.boot.test.autoconfigure.web.client.RestClientTest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.*;

@RestClientTest
class CompanyServiceTest {

    @Mock
    CompanyApiClient companyApiClient;

    @DisplayName("Given an uuid starting, it should return a company name generated by a HTTP call")
    @Test
    void getCompany() throws JsonProcessingException {

        String json = """
                {
                    "name": "Felucia"
                }
                """;
        CustomerDTO customer = new CustomerDTO("John", "Smith");
        Integer id = (customer.firstName() + customer.lastName()).length();
        when(companyApiClient.getCompanyName(id)).thenReturn(new ObjectMapper().readValue(json, CompanyDTO.class));

        Company company = new CompanyService(companyApiClient, true).getCompany(customer);

        verify(companyApiClient).getCompanyName(id);
        assertEquals("Felucia", company.name());
    }

    @DisplayName("Given an uuid starting, it should return an hardcoded company name")
    @Test
    void getHardcodedCompany() {

        CustomerDTO customer = new CustomerDTO("John", "Smith");
        Company company = new CompanyService(companyApiClient, false).getCompany(customer);

        verifyNoInteractions(companyApiClient);
        assertTrue(company.name().startsWith("Felucia-"));
    }

}